export const UI_OPEN = 'UI_OPEN';
export const UI_CLOSE = 'UI_CLOSE';
export const UI_SOFT_ENTER = 'UI_SOFT_ENTER';
export const UI_HARD_ENTER = 'UI_HARD_ENTER';
export const UI_STYLE_MESSENGER = 'UI_STYLE_MESSENGER';
export const UI_STYLE_FLOAT = 'UI_STYLE_FLOAT';
export const UI_STYLE_SIDEPANEL = 'UI_STYLE_SIDEPANEL';

export const TOGGLE_CHAT_STYLE = 'UI_STYLE_TOGGLE_CHAT_STYLE';
