export const CHAT_UNKNOWN = 'UNKNOWN';
export const CHAT_CONNECTED = 'CONNECTED';
export const CHAT_DISCONNECTED = 'DISCONNECTED';
export const CHAT_RECONNECTED = 'CONNECTED';
export const CHAT_RECONNECTING = 'RECONNECTING';
export const CHAT_MESSAGE_CLIENT = 'CHAT_MESSAGE_CLIENT'; // Check
export const CHAT_MESSAGE_OPERATOR = 'CHAT_MESSAGE_OPERATOR'; // Check

export const CHAT_CLIENT = 'CLIENT';
export const CHAT_OPERATOR = 'OPERATOR';
