export const CHAT_CONNECTED = 'CHAT_CONNECTED';
export const CHAT_DISCONNECTED = 'CHAT_DISCONNECTED';
export const CHAT_MESSAGE_CLIENT = 'CHAT_MESSAGE_CLIENT'; // Check
export const CHAT_MESSAGE_OPERATOR = 'CHAT_MESSAGE_OPERATOR'; // Check

export const CHAT_CLIENT = 'CLIENT';
export const CHAT_OPERATOR = 'OPERATOR';
